# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: ExtraCommands
main: uk.co.khobbits.extracommands.ExtraCommands
version: 1.1
website: http://khobbits.co.uk
description: Extra Commands
authors: [KHobbits]
depends: [Essentials]

commands:
   wc:
      description: Cycle through your warps
      usage: /<command>
      permission: extracommands.wc
   banlist:
      description: List of bans
      usage: /<command>
      permission: extracommands.banlist
   mutestatus:
      description: Show the status of a muted player
      usage: /<command>
      permission: extracommands.mutestatus
   jailstatus:
      description: Show the status of a jailed player
      usage: /<command>
      permission: extracommands.jailstatus